# Generated by Django 5.1.2 on 2024-12-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_artist_user_playlistsong'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('song', 'playlist')},
        ),
    ]
