# Generated by Django 5.1.2 on 2024-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_playlistsong_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='song',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
