# Generated by Django 5.1.2 on 2024-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_playlistsong_options_song_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums-covers/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='artists-covers/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='playlist-covers/'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='song-covers/'),
        ),
    ]
