# Generated by Django 5.1.2 on 2024-12-27 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_album_cover_artist_cover_playlist_cover_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.song'),
        ),
    ]
