# Generated by Django 5.1.2 on 2025-01-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_songfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.song'),
        ),
    ]
