# Generated by Django 5.1.2 on 2025-01-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_songfile_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='quality',
            field=models.SmallIntegerField(choices=[(0, '128kbps'), (1, '320kbps'), (2, 'LossLess'), (3, 'Hi-Fi')], default=1),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.song', to_field='slug'),
        ),
    ]
