# Generated by Django 5.1.2 on 2025-01-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_songfile_quality_alter_songfile_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.song', to_field='slug'),
        ),
    ]
